### ISSUE TITLE
Login credentials

### ISSUE THREAD

**Issue by philipsfuture** [odirleiborgert/borgert-cms#101]
whats the default login credentials..please provide..thank you

**Comment by odirleiborgert** [comment]
Hi @philipsfuture 
There is no default login, you need to create the first login following the steps:

https://github.com/odirleiborgert/borgert-cms/blob/master/docs/en/installation.md

Step 7:

Let access to tinker artisan to create the first user to access the CMS.

    php artisan borgert:user

OR

    php artisan tinker

$user = new App\User;
$user->name = 'Your Name';
$user->email = 'your@email.com';
$user->password = \Hash::make('YourPassword');
$user->status = 1;
$user->save();

**Comment by philipsfuture** [comment]
Thank you

**Comment by odirleiborgert** [comment]
@philipsfuture already using it on some project?
