### ISSUE TITLE
Implement ACL

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/borgert-cms#3]
Find some models to reach a model.

ROLES
- admin
- editor
- ...

**Comment by odirleiborgert** [comment]
https://gist.github.com/drawmyattention/8cb599ee5dc0af5f4246

**Comment by odirleiborgert** [comment]
https://github.com/spatie/laravel-permission

**Comment by RicardovanTongeren** [comment]
I use https://github.com/Zizaco/entrust for permissions and roles

**Comment by mehranrasulian** [comment]
Working on it. no problem to use a clean package?

**Comment by odirleiborgert** [comment]
No problem @mehranrasulian ... Thanks for you colaboration

**Comment by DeeJaVu** [comment]
Zizaco/entrust is not maintained anymore, instead you can use https://github.com/santigarcor/laratrust wich is a fork of entrust with all the bug fixes and more !
