### ISSUE TITLE
Upload de imagens

### ISSUE THREAD

**Issue by gusilveiramp** [odirleiborgert/borgert-cms#39]
Olá Odirlei, tudo bem?

Estou precisando de uma ajuda. Não estou entendendo muito bem como funciona o upload de imagens.
Eu vi que não existe uma tabela que armazena o caminho das imagens na pasta. Geralmente, em meus outros projetos, eu faço o upload da imagem, armazeno o caminho em uma tabela do BD e crio Thumbnails para utilizar ao longo do site.

No seu caso, vi que não existe uma tabela com o path das imagens. Como você chama as imagens? Por exemplo, como eu poderia utilizar as imagens da sessão "Produtos" ou exibir uma imagem específica na página do produto (no caso de um e-commerce)?

Desde já, te agradeço muito pelo trabalho a que está se prestando.

Abraço!

**Comment by odirleiborgert** [comment]
Olá @gusilveiramp 

Realmente a melhor forma seria gravar em uma tabela esses caminhos de imagens, porém como estava em busca de uma alternativa rápida para ter uma opção de upload ficou assim por enquanto, em um futuro próximo preciso refatorar toda essa parte de upload.

As imagens ficam gravadas na pasta `public/uploads/{path}/{id}` e para pegar as imagens de um determinado registro você pode fazer isso no seu controller:
```

// Importe o storage
use Storage;

// No método
public function index($id_produto)
{
      // Seu array de imagens daquela pasta
      $imagens = Storage::disk('uploads')->files('products/' . $id_produto. '/');
}

```

Se tiver qualquer dúvida posta ai...

Abraço,

**Comment by gusilveiramp** [comment]
Legal, entendi perfeitamente.

Muito obrigado!
Abraço!
