### ISSUE TITLE
Implement VueJS or ReactJS

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/borgert-cms#41]

**Comment by mehranrasulian** [comment]
What do you want to be done? any information?

**Comment by odirleiborgert** [comment]
Hi @mehranrasulian 
My idea is that I have an API, and the CMS made in VueJS, React or Angle consume this API

**Comment by mehranrasulian** [comment]
Hi @odirleiborgert ,
It seems that the CMS is not fully upgraded to Laravel 5.3.
We need to use Passport to consuming our API with Vue.js.

So I think it's better to consider a fully upgrade first.

**Comment by odirleiborgert** [comment]
Hi @mehranrasulian 

Did you see anything other than the passport? If you can make a list, or even if you can make a pull request with new implementations.

**Comment by mehranrasulian** [comment]
I have added a PR as WIP.

Probably, Vue.js is the best choice because of the community and because it's easy to use. Sorry but haven't used React.js before.

Also, for API, we may use [Fractal](fractal.thephpleague.com) so we can build a more consistent API.

**Comment by odirleiborgert** [comment]
@mehranrasulian thank you for your cooperation, continue collaborating whenever you can and have new ideas.
