### ISSUE TITLE
Create dashboard with informations

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/borgert-cms#46]
Informations:
- Users (count users)
- Posts (count posts)
- Comments (count comments)
- Pages (count pages)
- Mailbox (count unread messages)
- ChartJS to tell latest comments and posts
- List last comments unapproved

Use widgets inspinia - https://github.com/Niqpue/inspinia-master

**Comment by VagishVela** [comment]
@odirleiborgert This is designed for new contributors for OSS so maybe some more information maybe useful?

**Comment by odirleiborgert** [comment]
Hi @VagishVela 
Update issue...

**Comment by odirleiborgert** [comment]
Hi @VagishVela 
You are working on this issue?

**Comment by VagishVela** [comment]
@odirleiborgert I'm not, I was just providing some input. I haven't worked with Laravel before.
