### ISSUE TITLE
Check record was successfully

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/borgert-cms#50]
Check if the record was recorded successfully before moving/removing the folder with the images sent.

Methods: 
> upload()

Files
> app/Http/Controllers/Admin/Blog/PostsController.php
> app/Http/Controllers/Admin/Gallerys/GallerysController.php
> app/Http/Controllers/Admin/Products/ContentsController.php

**Comment by runz0rd** [comment]
@odirleiborgert mind if i take this one?

**Comment by odirleiborgert** [comment]
@runz0rd 
Feel free to improve the project and finalize the issue.

**Comment by runz0rd** [comment]
@odirleiborgert
Could you be more specific about "moving/removing the folder with the images sent"
I can see that files get deleted if they already exist, and thats being done before saving the upload
