### ISSUE TITLE
Confused about pages !

### ISSUE THREAD

**Issue by DeeJaVu** [odirleiborgert/borgert-cms#66]
Why does a page needs a category ?

**Comment by odirleiborgert** [comment]
Example:

Company (category)
  - History (page)
  - Mission (page)
  - Vision (page)

Services (category)
  - Service 1 (page)
  - Service 2 (page)
  - Service 3 (page)

**Comment by DeeJaVu** [comment]
i get it now, but can we make the category optional ?

**Comment by odirleiborgert** [comment]
Yes @DeeJaVu 
Do you want to implement this and do a PR?
