### ISSUE TITLE
Components folder is missing 

### ISSUE THREAD

**Issue by nouphaltklm** [odirleiborgert/borgert-cms#67]
The components folder is  under assets folder missing from the project and hence is not fully functional
e.g: http://localhost/borgert/assets/components/bootstrap/dist/css/bootstrap.min.css

**Comment by odirleiborgert** [comment]
Hi @nouphaltklm 

You install components with bower?

Step 2: bower install
https://github.com/odirleiborgert/borgert-cms/blob/master/docs/en/installation.md

**Comment by nouphaltklm** [comment]
@odirleiborgert Yes that did the job. Thanks for your quick reply and sincere apologies for my ignorance. :)

**Comment by odirleiborgert** [comment]
Feel free to take your doubts.

Feedbacks are always welcome ...;)
