### ISSUE TITLE
Projeto em Produção

### ISSUE THREAD

**Issue by monteiroands** [odirleiborgert/borgert-cms#68]
Estou tentando colocar o projeto em produção, mas apenas me retorna error 500.

**Comment by odirleiborgert** [comment]
Olá @monteiroands 
Chegou a verificar o que mostra no log?
/storage/logs/

**Comment by monteiroands** [comment]
Não mostra nada, não chega aparecer o erro.

**Comment by odirleiborgert** [comment]
Tem as pastas
- storage
       - app
       - framework
              - cache
              - sessions
              - views

Se não tiver crie, chegou a fazer todos os passos da instalação?
https://github.com/odirleiborgert/borgert-cms/blob/master/docs/pt-br/installation.md

**Comment by monteiroands** [comment]
Sim, existe todas essas pastas, estava rodando ele em local usando: php artisan serve

**Comment by odirleiborgert** [comment]
É o primeiro site em laravel que coloca em produção?

**Comment by monteiroands** [comment]
Não, os outros que trabalhei não usavam .env, e ainda usava .htaccess para a pasta /public.
Do mesmo jeito estou tentando, alguma dica?

**Comment by odirleiborgert** [comment]
Olá @monteiroands 
Vamos lá.. 

O .env continua valendo para esse projeto, conforme mostrado na instalação. Os dados como de banco de dados você configura tudo no config/database.php e remove as linhas do .env

O .htaccess também existe na pasta public

Tem acesso via SSH?
1. Rodou o composer install ?
2. Rodou o php artisan key:generate ?
3. Rodou php artisan migrate ?

Se quiser posso te ajudar por e-mail me passando algum acesso pra verificar o porque não está funcionando.

**Comment by monteiroands** [comment]
@odirleiborgert,

Gostaria sim, até para entender melhor.
Obrigado.

**Comment by odirleiborgert** [comment]
odirleiborgert@gmail.com
