### ISSUE TITLE
Upgrade laravel 5.5

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/borgert-cms#75]
This project use Laravel 5.4, necessarie upgrade to laravel 5.5

**Comment by SamsamBabadi** [comment]
I'll working on it

**Comment by odirleiborgert** [comment]
Hi @SamsamBabadi 

What do you think of suggesting some improvement in the project? Open an ISSUE and I will change the label to "Hacktoberfest" and I will wait for your PR.

Thanks

**Comment by SamsamBabadi** [comment]
OK
